Progress has stalled
Getting an error `TypeError: Cannot read property 'trim' of undefined`
(full error below). I'm not sure what is causing this. I can't find
where `trim` is used in the template that throws the error, and the
traceback is less than helpful. It could be something to do with
highlighting, or search, or something else entirely.

Going to change tack.

```
$ npm run build

> govuk_design_system@ build /Users/laurencedebruxelles/Code/design-system/govuk-design-system
> eleventy

Could not get HTML code from src/components/accordion/default/index.njk
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./src/components/accordion/index.md.njk

`TemplateContentRenderError` was thrown
> (./src/components/accordion/index.md.njk) [Line 68, Column 23]
  TypeError: Cannot read property 'trim' of undefined

`Template render error` was thrown:
    Template render error: (./src/components/accordion/index.md.njk) [Line 68, Column 23]
      TypeError: Cannot read property 'trim' of undefined
        at Object._prettifyError (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/lib.js:36:11)
        at /Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:563:19
        at eval (eval at _compile (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:13:11)
        at /Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:613:9
        at Template.root [as rootRenderFunc] (eval at _compile (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:442:3)
        at Template.getExported (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:611:10)
        at eval (eval at _compile (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:12:5)
        at createTemplate (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:315:9)
        at handle (/Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:327:11)
        at /Users/laurencedebruxelles/Code/design-system/govuk-design-system/node_modules/nunjucks/src/environment.js:339:9
Wrote 0 files in 0.55 seconds (v0.12.1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! govuk_design_system@ build: `eleventy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the govuk_design_system@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/laurencedebruxelles/.npm/_logs/2021-06-30T09_36_20_971Z-debug.log
```